### ISSUE TITLE
请教两个问题

### ISSUE THREAD

**Issue by Ztiany** [gaoneng102/ubuntu-for-Android#1]
1 你的shadowsocks是用的[shadowsocks-qt5](https://github.com/shadowsocks/shadowsocks-qt5)么，是否可以正常翻X呢？

谢谢

**Comment by gaoneng102** [comment]
@Ztiany 需要购买账号的。我是这个网址购买的 https://www.shadowsocks.com/ 
但是在19大期间维护，11月1号就可以正常使用了。
