### ISSUE TITLE
如何重置Ununtu 16.04 系统？

### ISSUE THREAD

**Issue by MoeRookie** [gaoneng102/ubuntu-for-Android#2]
您好，本人一名Andorid开发者，近期因为个人原因导致电脑在Win环境下无法关机了；
目前只能用Linux才可以，不知道是不是上天的安排，不过，我还是在Linux系统上一名惨烈的大白；
我跟着您教程走的时候，一开始设置了源，设置源之后，就各种装不上软件了；
所以，我目前能想到的办法是：重置系统，不知道您能不能给出个解决方案？

**Comment by gaoneng102** [comment]
@MoeRookie 有报什么错误吗，或者有错误截图没有，命令行中一般都有错误日志输出，发出来看下

**Comment by MoeRookie** [comment]
已经解决了，又进行了一次系统重装
